---
apiVersion: v1
kind: Service
metadata:
  name: blue-active
  namespace: argocd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: blue-preview
  namespace: argocd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
